name: Update Pump Tokens

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run scraper
      run: python scripts/scrape_pump.py

    - name: Move output before switching branch
      run: mv pump_tokens.json /tmp/pump_tokens.json

    - name: Switch to gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Restore output on gh-pages
      run: mv /tmp/pump_tokens.json pump_tokens.json


    - name: Commit and push pump_tokens.json
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add pump_tokens.json
        git commit -m "Auto-update pump_tokens.json" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} gh-pages
